# Generated by Django 5.2 on 2026-05-26 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='PENDING', max_length=20)),
                ('analyst_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='normalization.normalizedrecord')),
            ],
            options={
                'db_table': 'review_items',
            },
        ),
    ]
