# Generated by Django 5.2 on 2026-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawrecord',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
